spring.application.name=skillhive-backend
spring.datasource.url=jdbc:mysql://localhost:3306/skillhive
spring.datasource.username=root
spring.datasource.password=Chintu@25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080